services:
      # Optionally include Open-WebUI
    open-webui:
        image: 'ghcr.io/open-webui/open-webui:main'
        restart: always
        container_name: open-webui
        volumes:
            - './data_open-webui:/app/backend/data'
# Uncomment this for external ollama
#       environment:
#           - 'OLLAMA_BASE_URL=https://example.com'
# Comment or uncomment this for locally hosted ollama
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '3000:8080'
        depends_on:
            - ollama
