services:
    ollama:
        restart: unless-stopped
        image: ollama/ollama
        container_name: ollama
        ports:
            - '11434:11434'
        volumes:
            - './data:/root/.ollama'
            - './data_custom-models:/opt/custom_models'
        deploy:
            resources:
              reservations:
                devices:
                  - driver: nvidia
                    device_ids: ['0', '1']
                 #  device_ids: ['0']
                    capabilities: [gpu]

