services:
  pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      volumes:
        # Must be owned by 5050 <https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#mapped-files-and-directories>
        # chown -R 5050:5050 ./data/
        - ./data/pgadmin:/var/lib/pgadmin
      ports:
        - "5050:80"
